name: 'Kakarot CI'
description: 'AI-powered unit test generation for pull requests'
author: 'David Jansen / Lokardo Labs'
branding:
  icon: 'activity'
  color: 'green'

inputs:
  api-key:
    description: 'LLM API key (OpenAI, Anthropic, or Google)'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  provider:
    description: 'LLM provider (openai, anthropic, or google)'
    required: false
  model:
    description: 'Model name'
    required: false
    
outputs:
  tests-generated:
    description: 'Number of tests generated'
  tests-failed:
    description: 'Number of tests that failed'
  targets-processed:
    description: 'Number of targets processed'

runs:
  using: 'node20'
  main: 'dist/index.js'

